# Generated by Django 5.0.1 on 2024-01-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_user_source_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="sink",
            name="budget",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="transactions.sink",
            ),
        ),
    ]
