# Generated by Django 5.0.1 on 2024-01-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_sink_budget_alter_transaction_sink"),
    ]

    operations = [
        migrations.AddField(
            model_name="sink",
            name="sink_type",
            field=models.CharField(
                choices=[("expense", "expense"), ("shadow", "shadow")],
                default="expense",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
